#!/bin/bash

NAME="bine_www"                                     # Name of the application
DJANGODIR=/home/django/bine_www                     # Django project directory
SOCKFILE=/home/django/run/gunicorn.sock             # we will communicate using this unix socket
USER=django                                         # the user to run as
NUM_WORKERS=3                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=bine_www.settings            # which settings file should Django use
DJANGO_WSGI_MODULE=bine_www.wsgi                    # WSGI module name
VIRTUAL_ENV_DIR=/home/django/env

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/django/env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ${VIRTUAL_ENV_DIR}/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
